### ISSUE TITLE
TransportationCostOptimization.cpp

### ISSUE THREAD

**Issue by NadetoDG** [ArchitParnami/Transportation-Cost-Optimizer#1]
I try to create a new console App with the code from TransportationCostOptimization.cpp file but I get many errors.

**Comment by ArchitParnami** [comment]
Hi,

Are you running it on windows? There is an include for windows.h in the program as it uses windows console. Please share the error file.

**Comment by NadetoDG** [comment]
Hi,
Yes I am running it in windows. I’ve create a new “Win32 Application Wizard” project for C++ and paste you code inside the project file.

[errors.txt](https://github.com/ArchitParnami/Transportation-Cost-Optimizer/files/990845/errors.txt)

**Comment by NadetoDG** [comment]
ConsoleApplication1.cpp actually is TransportationCostOptimization.cpp

**Comment by ArchitParnami** [comment]
Hello, 

It seems like you are running it in Microsoft Visual Studio which uses its own visual c++ compiler. I wrote this using code blocks which uses GCC/G++ compiler. If its urgent you can just download code blocks, open the C++ file in it and compile, it should work.
Here is the link. 
http://www.codeblocks.org/downloads/26

However it should also work with VS. It must be some compiler flag/settings which is forcing some rule checking. I will check.

**Comment by NadetoDG** [comment]
Hello,

Thanks for the answer. If you find something solution for VS please let me know.

**Comment by ArchitParnami** [comment]
Hello,

I tried running this on VS &  got the same errors you reported. Most of the errors are of type like "Using uninitialized variables" or "Using a variable where a constant is enforced like in array initialization" which are not really errors but good coding practices enforced as rules by VC++ compiler. Unfortunately I couldn't find an option to turn off these checks. So the only options which are left are:
1. Fix these to make it work with MSVC++ compiler
2. Use GCC compiler which doesn't enforce these rules.

You can go ahead and try option 1. But I would prefer Option 2 as this is really an old project for me and it still works fine with GCC so I don't need to fix anything.

Thank you for your interest in this project! 
All the best!
